---
- name: Kibana archive available
  get_url:
    dest=/opt
    url=https://download.elastic.co/kibana/kibana/kibana-{{ elk_kibana.version }}.tar.gz
    owner={{ elk_user }} group={{ elk_user }}
  sudo: yes
  register: new_archive_downloaded

- name: Kibana archive uncompressed
  unarchive:
    src=/opt/kibana-{{ elk_kibana.version }}.tar.gz
    dest=/opt copy=no
    owner={{ elk_user }} group={{ elk_user }}
  sudo: yes
  when: new_archive_downloaded|changed

- name: Uncompressed Kibana linked to path
  file:
    src=/opt/kibana-{{ elk_kibana.version }}
    path={{ elk_kibana.path }} state=link
    owner={{ elk_user }} group={{ elk_user }}
  sudo: yes

- name: Kibana files ownership
  file:
    path=/opt/kibana-{{ elk_kibana.version }}
    state=directory
    owner={{ elk_user }} group={{ elk_user }} recurse=yes
  changed_when: False
  sudo: yes