---
- name: Logstash apt repo
  apt_repository: repo="deb http://packages.elastic.co/logstash/{{ elk_logstash.version }}/{{ ansible_os_family|lower }} stable main"
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: Install logstash apt packages
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
    - logstash
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: Logstash conf file
  template:
    src={{ item.src }}
    dest=/etc/logstash/conf.d/{{ item.dest }}
    owner=root group=root mode=644
  with_items: elk_logstash.configs
  sudo: yes

- name: Logstash pattern files
  template:
    src={{ item.src }}
    dest=/opt/logstash/patterns/{{ item.dest }}
    owner=root group=root mode=644
  with_items: elk_logstash.patterns
  sudo: yes
  when: elk_logstash.patterns is defined
